name: Type Checks

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '14 5 * * 1,3,5'

permissions:
  contents: read

jobs:
  type-check:
    uses: voxpelli/ghatemplates/.github/workflows/type-check.yml@main
    with:
      ts-versions: ${{ github.event.schedule && 'next' || '4.5,4.6,4.7,4.8,next' }}
      ts-libs: 'es2020;esnext'
